apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service.devops.svc.cluster.local:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true
