version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: student-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  student-app:
    build: .
    image: student-app
    container_name: student-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8089:8080"
    restart: always

volumes:
  mysql_data:
