apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: angular-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
